celebs = [
    'George Clooney',
    'Barack Obama',
    'Larry David',
    'Keira Knightley',
    'Vin Diesel',
    'Jessica Alba',
    'Jordana Brewster',
    'Elsa Pataky',
    'Jennifer Lopez',
    'Shailene Woodley',
    'Scarlett Johansson',
    'Paul Wesley',
    'Ian Somerhalder',
    'Sara Canning',
    'Christian Bale',
    'Kate Upton',
    'Cameron Diaz',
    'Brad Pitt',
    'Angelina Jolie',
    'Jennifer Aniston',
    'Leonardo DiCaprio',
    'David Giuntoli',
    'Daniel Gillies',
    'Danielle Campbell',
    'Janina Gavankar',
    'Katy Perry',
    'Katie McGrath',
    'Nathalie Kelley',
    'Liam Neeson',
    'Michelle Dockery',
    'William Fichtner',
    'Emma Stone',
    'Kit Harington',
    'Margot Robbie',
    'Silas Weir Mitchell',
    'Hugh Jackman',
    'Natalie Portman',
    'Chris Hemsworth',
    'Michael Caine',
    'Anne Hathaway',
    'Keanu Reeves',
    'Bruce Willis',
    'Morgan Freeman',
    'Will Smith',
    'Jack Nicholson',
    'Denzel Washington',
    'Jim Carrey',
    'Mel Gibson',
    'Sylvester Stallone',
    'Kevin Costner',
    'Will Ferrell',
    'Johnny Depp',
    'Jodie Foster'
    'Nicole Kidman',
    'Kristen Stewart',
    'Reese Witherspoon',
    'Chris Pratt',
    'Samuel L. Jackson',
    'Bradley Cooper',
    'Stan Lee',
    'Idris Elba',
    'Danny DeVito',
    'Robin Williams',
    'James Earl Jones',
    'John Cusack',
    'Betty White',
    'Michael Douglas',
    'Anthony Hopkins',
    'Bill Murray',
    'Nicolas Cage',
    'Julianne Moore',
    'Jimmy Carter',
    'Bill Clinton',
    'Taylor Swift',
    'Ariana Grande',
    'Lana Del Rey',
    'Kelly Clarkson',
    'Britney Spears',
    'Selena Gomez',
    'Gwen Stefani',
    'Chester Bennington',
    'Kurt Cobain',
    'John Lennon',
    'John Legend',
    'Drake'
    'Harry Styles',
    'Celine Dion',
    'Snoop Dogg',
    'XXXTentacion',
    'Travis Scott',
    'Christina Aguilera',
    'Shakira',
    'Mariah Carey',
    'Miley Cyrus',
    'David Bowie',
    'Rihanna',
]

characters = [
    'Indiana Jones',
    'Mr. Bean',
    'Tyler Durden'
    'Ellen Ripley',
    'Walter White',
    'John McClane',
    'Sarah Connor',
    'Jack Sparrow',
    'Tony Stark',
    'Clarice Starling',
    'Atticus Finch',
    'Vito Corleone',
    'Travis Bickle',
    'Ethan Hunt',
    'Jack Dawson',
    'Rhett Butler',
    'Jules Winnfield',
    'Vincent Vega',
    'Andy Dufresne',
    'Howard Hughes',
    'Jordan Belfort',
    'Chris Gardner',
]
